[project]
name = "llm-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.0",
    "deepagents>=0.4.1",
    "deepeval>=3.8.4",
    "evaluate>=0.4.6",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.11",
    "langchain-openai>=1.1.9",
    "langchain-text-splitters>=1.1.0",
    "scikit-learn>=1.8.0",
    "tavily-python>=0.7.21",
]
